# ==============================
# Tarea Corta 1 — Inteligencia Artificial
# Integrantes: María Felix Mendez Abarca, Christian Rivas y Jozafath Perez
# Descripción: Configuración del descubrimiento de pruebas y la ruta del proyecto.
# ==============================

[pytest]
testpaths = tests
pythonpath = .
